import os
import csv
import asyncio
import time
import base64
import re
import requests
import edge_tts
import logging
from pathlib import Path

# ==============================================================================
# 1. DYNAMIC PATHS (Portability)
# ==============================================================================
# Resolves the current directory to ensure the script runs smoothly on any OS
BASE_DIR = Path(__file__).parent.parent.resolve()
DATA_DIR = BASE_DIR / "data"
DESKTOP_DIR = Path.home() / "Desktop"
LOG_FILE = BASE_DIR / "ankibot.log"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(),
    ],
)

# ==============================================================================
# 2. CONFIGURATIONS
# ==============================================================================
# Matches the filenames generated by agent_part_1.py
GERMAN_CONFIG = {
    "language": "German",
    "source_files": [
        DATA_DIR / "csv" / "de_example.csv",  # Updated to match part_1.py
        DESKTOP_DIR / "German_manual_correction.txt",
        DESKTOP_DIR / "German_Pro_Request.txt",
    ],
    "main_csv_path": DATA_DIR / "csv" / "DEUTSCH.csv",
    "deck_name": "Deutsch",
    "note_type": "German_Cloze",  # Updated to English
    "field_sentence": "Sentence_German",  # Updated to English
    "voice": "de-DE-ConradNeural",
}

ENGLISH_CONFIG = {
    "language": "English",
    "source_files": [
        DATA_DIR / "csv" / "en_example.csv",  # Updated to match part_1.py
        DESKTOP_DIR / "English_Pro_Request.txt",
    ],
    "main_csv_path": DATA_DIR / "csv" / "ENGLISH.csv",
    "deck_name": "English",
    "note_type": "English_Cloze",  # Updated to English
    "field_sentence": "Sentence_English",  # Updated to English
    "voice": "en-US-JennyNeural",
}


# ==============================================================================
# 3. HELPER FUNCTIONS
# ==============================================================================
def clean_cloze_tags_for_tts(sentence):
    """
    Strips Anki cloze formatting (e.g., {{c1::word::hint}}) from the sentence
    so the TTS engine reads the text naturally without spelling out brackets.
    """
    return re.sub(r"\{\{c\d+::(.*?)(?:::.*?)?\}\}", r"\1", sentence)


async def generate_tts_async(text, voice, filename):
    """Generates an MP3 file asynchronously using Microsoft Edge TTS."""
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(filename)


def invoke_anki_api(action, **params):
    """
    Sends a payload to the local AnkiConnect REST API.
    Provides robust error handling if Anki is closed or unresponsive.
    """
    request_json = {"action": action, "params": params, "version": 6}
    try:
        response = requests.post("http://localhost:8765", json=request_json).json()
        if response.get("error"):
            raise Exception(response["error"])
        return response["result"]
    except requests.exceptions.ConnectionError:
        raise Exception(
            "Anki connection failed! Please ensure Anki is running in the background."
        )


def upload_media_to_anki(filename):
    """Converts the MP3 file to Base64 and injects it into Anki's media collection."""
    with open(filename, "rb") as f:
        b64_data = base64.b64encode(f.read()).decode("utf-8")
    invoke_anki_api("storeMediaFile", filename=filename, data=b64_data)
    os.remove(filename)  # Cleanup local audio file after injection


def append_to_master_csv(file_path, flashcards, field_sentence_name):
    """Appends successfully injected flashcards to the Master Archival CSV."""
    file_exists = os.path.exists(file_path)
    with open(file_path, "a", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter="|")
        if not file_exists:
            # ENGLISH HEADERS APPLIED HERE
            writer.writerow(
                [field_sentence_name, "Base_Word", "Meaning", "Translation"]
            )
        for card in flashcards:
            writer.writerow(
                [
                    card.get("sentence", ""),  # Updated keys
                    card.get("base_word", ""),  # Updated keys
                    card.get("meaning", ""),  # Updated keys
                    card.get("translation", ""),  # Updated keys
                ]
            )


def clear_daily_source_file(file_path):
    """
    Stateful cleanup: Empties the processed files to prevent duplicate injections.
    Retains the header for CSV files, entirely clears TXT files.
    """
    file_path = str(file_path)
    if not os.path.exists(file_path):
        return

    if file_path.endswith(".txt"):
        open(file_path, "w", encoding="utf-8").close()
    else:
        # Keep CSV header
        with open(file_path, "r", encoding="utf-8") as f:
            header = f.readline()
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(header)


# ==============================================================================
# 4. CORE ENGINE (PART 2: HYBRID INGESTION & INJECTION)
# ==============================================================================
def process_daily_sources(config):
    """
    Reads mixed sources (CSV & TXT), generates TTS, pushes to Anki DB via API,
    archives the data, and performs stateful cleanup.
    """
    source_files = config["source_files"]
    cards = []
    lang = config["language"]

    # Step 1: Hybrid Data Ingestion (Parse all valid sources)
    for file_path in source_files:
        if not os.path.exists(file_path):
            continue

        with open(file_path, "r", encoding="utf-8") as f:
            if str(file_path).endswith(".txt"):
                # Headerless parsing for manual TXT fallbacks
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    parts = line.split("|")
                    if len(parts) >= 4:
                        cards.append(
                            {
                                "sentence": " ".join(parts[0].split()),  # Updated keys
                                "base_word": " ".join(parts[1].split()),  # Updated keys
                                "meaning": " ".join(parts[2].split()),  # Updated keys
                                "translation": " ".join(
                                    parts[3].split()
                                ),  # Updated keys
                            }
                        )
            else:
                # Header-aware parsing for automated CSVs
                reader = csv.reader(f, delimiter="|")
                next(reader, None)  # Skip header
                for row in reader:
                    if len(row) >= 4:
                        cards.append(
                            {
                                "sentence": " ".join(row[0].split()),  # Updated keys
                                "base_word": " ".join(row[1].split()),  # Updated keys
                                "meaning": " ".join(row[2].split()),  # Updated keys
                                "translation": " ".join(row[3].split()),  # Updated keys
                            }
                        )

    if not cards:
        logging.info(f"ℹ️ No pending cards found for {lang}.")
        return False

    logging.info(f"\n🚀 Processing {len(cards)} cards for {lang}...")

    # Step 2: TTS Generation and Anki Injection
    successful_cards = []
    for idx, card in enumerate(cards):
        clean_sentence = clean_cloze_tags_for_tts(card["sentence"])  # Updated key
        audio_filename = f"tts_{lang}_{idx}_{int(time.time())}.mp3"

        try:
            # 2.1 Async TTS Generation
            asyncio.run(
                generate_tts_async(clean_sentence, config["voice"], audio_filename)
            )

            # 2.2 Upload Base64 Audio to Anki
            upload_media_to_anki(audio_filename)

            # 2.3 Create Anki Note Payload
            note = {
                "deckName": config["deck_name"],
                "modelName": config["note_type"],
                "fields": {
                    # Note: These exact field names MUST exist in your Anki Note Type settings!
                    config["field_sentence"]: card["sentence"],
                    "Base_Word": card[
                        "base_word"
                    ],  # Updated to match part_1 logic (Assuming Anki field is named Base_Word)
                    "Meaning": card["meaning"],  # Assuming Anki field is Meaning
                    "Translation": f"{card['translation']} [sound:{audio_filename}]",  # Assuming Anki field is Translation
                },
                "options": {"allowDuplicate": False},
                "tags": [f"Part2_{lang}", "Automated_Pipeline"],
            }

            # 2.4 Inject Note
            invoke_anki_api("addNote", note=note)
            logging.info(
                f"   ✅ {card['base_word']} -> Injected to Anki"
            )  # Updated key
            successful_cards.append(card)
            time.sleep(1)  # Brief pause to respect local API processing

        except Exception as e:
            logging.error(
                f"   ❌ Error on ({card.get('base_word')}): {e}"
            )  # Updated key

    if not successful_cards:
        logging.error(f"❌ {lang} injection failed completely.")
        return False

    # Step 3: Archival
    append_to_master_csv(
        config["main_csv_path"], successful_cards, config["field_sentence"]
    )
    logging.info(f"📚 {len(successful_cards)} cards archived to Master CSV.")

    # Step 4: Stateful Cleanup
    for file_path in source_files:
        if os.path.exists(file_path):
            clear_daily_source_file(file_path)
            logging.info(f"🗑️ Source file cleaned: {file_path.name}")

    return True


# ==============================================================================
# 5. MAIN EXECUTION
# ==============================================================================
def main():
    logging.info(
        "🌟 Autonomous Language Factory - PART 2 (TTS & Injection) starting...\n"
    )

    # Pre-flight check: Ensure Anki local API is reachable
    try:
        invoke_anki_api("version")
        logging.info("✅ AnkiConnect API connected successfully.\n")
    except Exception as e:
        logging.error(f"❌ AnkiConnect Error: {e}")
        return

    # Process German and English pipelines sequentially
    process_daily_sources(GERMAN_CONFIG)
    process_daily_sources(ENGLISH_CONFIG)

    logging.info("\n🎉 All injection processes completed successfully!")


if __name__ == "__main__":
    main()
